In [6]:
import pandas as pd
import numpy as np

from sklearn.model_selection import GridSearchCV, cross_val_score
from alg4 import model

In [7]:
DATA='ugrin2020-vehiculo-usado-multiclase/'
TRAIN=DATA+'train.csv'
TEST=DATA+'test.csv'

PREPROCESSED_DATA='preprocessed_data/'
RESULTS='results/'

In [8]:
# Carga de datos ya procesados
X=np.load(PREPROCESSED_DATA+'binScale.npz')
train = X['arr_0']
label = X['arr_1']
test = X['arr_2']
X.close()

In [15]:
param_grid={'n_neighbors':[1,2,3,5,7],'weights':['uniform','distance'],'metric':['euclidean','manhattan']}
searcher = GridSearchCV(model, param_grid, n_jobs=4,verbose=15,cv=3)
search = searcher.fit(train,label)

Fitting 3 folds for each of 20 candidates, totalling 60 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   1 tasks      | elapsed:    2.1s
[Parallel(n_jobs=4)]: Done   2 tasks      | elapsed:    2.2s
[Parallel(n_jobs=4)]: Done   3 tasks      | elapsed:    2.2s
[Parallel(n_jobs=4)]: Done   4 tasks      | elapsed:    2.2s
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    3.8s
[Parallel(n_jobs=4)]: Done   6 tasks      | elapsed:    4.3s
[Parallel(n_jobs=4)]: Done   7 tasks      | elapsed:    4.5s
[Parallel(n_jobs=4)]: Done   8 tasks      | elapsed:    4.8s
[Parallel(n_jobs=4)]: Done   9 tasks      | elapsed:    6.1s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    6.1s
[Parallel(n_jobs=4)]: Done  11 tasks      | elapsed:    6.6s
[Parallel(n_jobs=4)]: Done  12 tasks      | elapsed:    6.7s
[Parallel(n_jobs=4)]: Done  13 tasks      | elapsed:    8.0s
[Parallel(n_jobs=4)]: Done  14 tasks      | elapsed:    8.2s
[Parallel(n_jobs=4)]: Done  15 tasks      | elapsed:    8.7s
[Parallel(n_jobs=4)]: Done  16 tasks      | elapsed:    8.8s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    9.9s
[Parallel(n_jobs=4)]: Done  18 tasks      | elapsed:   10.1s
[Parallel(n_jobs=4)]: Done  19 tasks      | elapsed:   11.1s
[Parallel(n_jobs=4)]: Done  20 tasks      | elapsed:   11.3s
[Parallel(n_jobs=4)]: Done  21 tasks      | elapsed:   12.0s
[Parallel(n_jobs=4)]: Done  22 tasks      | elapsed:   12.3s
[Parallel(n_jobs=4)]: Done  23 tasks      | elapsed:   12.8s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:   13.0s
[Parallel(n_jobs=4)]: Done  25 tasks      | elapsed:   14.6s
[Parallel(n_jobs=4)]: Done  26 tasks      | elapsed:   14.8s
[Parallel(n_jobs=4)]: Done  27 tasks      | elapsed:   15.1s
[Parallel(n_jobs=4)]: Done  28 tasks      | elapsed:   15.1s
[Parallel(n_jobs=4)]: Done  29 tasks      | elapsed:   16.7s
[Parallel(n_jobs=4)]: Done  30 tasks      | elapsed:   16.9s
[Parallel(n_jobs=4)]: Done  31 tasks      | elapsed:   17.2s
[Parallel(n_jobs=4)]: Done  32 tasks      | elapsed:   17.4s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:   18.5s
[Parallel(n_jobs=4)]: Done  34 tasks      | elapsed:   18.6s
[Parallel(n_jobs=4)]: Done  35 tasks      | elapsed:   18.8s
[Parallel(n_jobs=4)]: Done  36 tasks      | elapsed:   19.1s
[Parallel(n_jobs=4)]: Done  37 tasks      | elapsed:   20.4s
[Parallel(n_jobs=4)]: Done  38 tasks      | elapsed:   20.5s
[Parallel(n_jobs=4)]: Done  39 tasks      | elapsed:   21.0s
[Parallel(n_jobs=4)]: Done  40 tasks      | elapsed:   21.1s
[Parallel(n_jobs=4)]: Done  41 tasks      | elapsed:   22.3s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:   22.3s
[Parallel(n_jobs=4)]: Done  43 tasks      | elapsed:   23.1s
[Parallel(n_jobs=4)]: Done  44 tasks      | elapsed:   23.3s
[Parallel(n_jobs=4)]: Done  45 tasks      | elapsed:   24.3s
[Parallel(n_jobs=4)]: Done  46 tasks      | elapsed:   24.4s
[Parallel(n_jobs=4)]: Done  47 tasks      | elapsed:   25.1s
[Parallel(n_jobs=4)]: Done  48 tasks      | elapsed:   25.5s
[Parallel(n_jobs=4)]: Done  49 tasks      | elapsed:   26.8s
[Parallel(n_jobs=4)]: Done  50 tasks      | elapsed:   26.9s
[Parallel(n_jobs=4)]: Done  51 tasks      | elapsed:   27.5s
[Parallel(n_jobs=4)]: Done  52 tasks      | elapsed:   27.6s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:   29.0s
[Parallel(n_jobs=4)]: Done  58 out of  60 | elapsed:   31.6s remaining:    1.1s
[Parallel(n_jobs=4)]: Done  60 out of  60 | elapsed:   32.3s finished

In [16]:
pd.DataFrame(search.cv_results_)[['param_metric','param_n_neighbors','param_weights','mean_test_score','rank_test_score']].sort_values(by='rank_test_score')

,param_metric,param_n_neighbors,param_weights,mean_test_score,rank_test_score
13,manhattan,2,distance,0.861040,1
11,manhattan,1,distance,0.860931,2
10,manhattan,1,uniform,0.860931,2
3,euclidean,2,distance,0.853917,4
0,euclidean,1,uniform,0.853808,5
1,euclidean,1,distance,0.853808,5
15,manhattan,3,distance,0.841206,7
17,manhattan,5,distance,0.836275,8
5,euclidean,3,distance,0.831671,9
19,manhattan,7,distance,0.830686,10
7,euclidean,5,distance,0.821261,11
9,euclidean,7,distance,0.816439,12
12,manhattan,2,uniform,0.816328,13
14,manhattan,3,uniform,0.815343,14
2,euclidean,2,uniform,0.807671,15
4,euclidean,3,uniform,0.803287,16
16,manhattan,5,uniform,0.799453,17
18,manhattan,7,uniform,0.790138,18
6,euclidean,5,uniform,0.779069,19
8,euclidean,7,uniform,0.761315,20

In [17]:
print('Mejores parámetros:', search.best_params_)
print('Mejor puntuación:', search.best_score_)
model.set_params(**(search.best_params_))

Mejores parámetros: {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'distance'}
Mejor puntuación: 0.861040431943222

KNeighborsClassifier(metric='manhattan', n_jobs=4, n_neighbors=2,
                     weights='distance')

In [18]:
scores=cross_val_score(model, train, label)
print(scores)
print(np.mean(scores))

[0.8690411  0.87287671 0.87561644 0.88164384 0.87616438]
0.8750684931506848

In [ ]:
model.fit(train,label)